"""empty message

Revision ID: 4421f8d7a9b1
Revises: 0a3bc86eb04a
Create Date: 2025-09-24 20:44:42.263697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4421f8d7a9b1'
down_revision = '0a3bc86eb04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
