"""empty message

Revision ID: 55b886600c5a
Revises: 4421f8d7a9b1
Create Date: 2025-09-24 20:56:27.325810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b886600c5a'
down_revision = '4421f8d7a9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('barcode',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
