"""empty message

Revision ID: c39c7cf08dc3
Revises: 55b886600c5a
Create Date: 2025-09-24 21:14:17.220425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39c7cf08dc3'
down_revision = '55b886600c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('iid', name=op.f('pk_items')),
    sa.UniqueConstraint('barcode', name=op.f('uq_items_barcode'))
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('iid', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('barcode', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('iid'),
    sa.UniqueConstraint('barcode', name=op.f('uq_item_barcode'))
    )
    op.drop_table('items')
    # ### end Alembic commands ###
